name: PDF Bot

on:
  workflow_dispatch:
  push:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Packages
      run: |
        pip install -r requirements.txt

    - name: Run Bot
      run: python bot.py
